/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as SurahIdRouteImport } from './routes/surah.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/reset-password'
    | '/articles/$slug'
    | '/c/$slug'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/reset-password'
    | '/articles/$slug'
    | '/c/$slug'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/reset-password'
    | '/articles/$slug'
    | '/c/$slug'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CSlugRoute: typeof CSlugRoute
  PSlugRoute: typeof PSlugRoute
  SurahIdRoute: typeof SurahIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CSlugRoute: CSlugRoute,
  PSlugRoute: PSlugRoute,
  SurahIdRoute: SurahIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
